services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    restart: always
  backend:
    build: .
    container_name: expense_container
    ports:
      - 8080:8080
    environment:
      - db-url=jdbc:postgresql://db:5432/postgres
      - db-username=postgres
      - db-password=admin
    depends_on:
      - db
    restart: always

